# Generated by Django 3.1.7 on 2021-05-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_reviews_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='pieces',
            new_name='hours',
        ),
        migrations.AlterField(
            model_name='item',
            name='instructions',
            field=models.CharField(default='type you option', max_length=250),
        ),
        migrations.AlterField(
            model_name='item',
            name='labels',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('health', 'Health'), ('trans', 'Transport'), ('Mail', 'Mail'), ('Electric', 'Electronics'), ('emergency', 'Emergency')], max_length=25),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='type_model'),
        ),
    ]
