# Generated by Django 3.1.7 on 2021-05-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210518_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label_colour',
            field=models.CharField(blank=True, choices=[('danger', 'danger-emergency'), ('success', 'success-home'), ('primary', 'primary-health'), ('info', 'info-mail'), ('warning', 'warning-electric'), ('default', 'default-transport')], max_length=15),
        ),
        migrations.AlterField(
            model_name='item',
            name='labels',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('health', 'Health'), ('transport', 'Transport'), ('mail', 'Mail'), ('electric', 'Electronics'), ('emergency', 'Emergency')], max_length=25),
        ),
    ]
